import type { ChartIndicator } from "@/types/market";

// Default chart indicator configurations
export const defaultIndicators: ChartIndicator[] = [
  {
    id: "sma20",
    name: "Simple Moving Average (20)",
    shortName: "SMA 20",
    type: "overlay",
    enabled: true,
    color: "hsl(var(--info))",
    params: { period: 20 },
  },
  {
    id: "sma50",
    name: "Simple Moving Average (50)",
    shortName: "SMA 50",
    type: "overlay",
    enabled: false,
    color: "hsl(var(--warning))",
    params: { period: 50 },
  },
  {
    id: "ema12",
    name: "Exponential Moving Average (12)",
    shortName: "EMA 12",
    type: "overlay",
    enabled: false,
    color: "hsl(var(--accent))",
    params: { period: 12 },
  },
  {
    id: "ema26",
    name: "Exponential Moving Average (26)",
    shortName: "EMA 26",
    type: "overlay",
    enabled: false,
    color: "hsl(var(--primary))",
    params: { period: 26 },
  },
  {
    id: "bb",
    name: "Bollinger Bands",
    shortName: "BB",
    type: "overlay",
    enabled: false,
    color: "hsl(var(--terminal-cyan))",
    params: { period: 20, stdDev: 2 },
  },
  {
    id: "vwap",
    name: "Volume Weighted Avg Price",
    shortName: "VWAP",
    type: "overlay",
    enabled: false,
    color: "hsl(var(--terminal-amber))",
    params: {},
  },
  {
    id: "rsi",
    name: "Relative Strength Index",
    shortName: "RSI",
    type: "oscillator",
    enabled: false,
    color: "hsl(var(--accent))",
    params: { period: 14 },
  },
  {
    id: "macd",
    name: "MACD",
    shortName: "MACD",
    type: "oscillator",
    enabled: false,
    color: "hsl(var(--info))",
    params: { fast: 12, slow: 26, signal: 9 },
  },
];
